#!/usr/bin/env bash
# Add the subdomain www to your domain, point it to your lb-01 IP
# Add the subdomain lb-01 to your domain, point it to your lb-01 IP
# Add the subdomain web-01 to your domain, point it to your web-01 IP
# Add the subdomain web-02 to your domain, point it to your web-02 IP
# Bash script must accept 2 arguments domain and subdomain

function audit_subdomain {
    local domain="$1"
    local subdomain="$2"
    
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        case "$sub" in
            "www")
                # Set the desired IP address for www
                destination="54.167.153.71"
                ;;
            "lb-01")
                # Set the desired IP address for lb-01
                destination="54.167.153.71"
                ;;
            "web-01")
                # Set the desired IP address for web-01
                destination="54.174.92.204"
                ;;
            "web-02")
                # Set the desired IP address for web-02
                destination="54.172.150.212"
                ;;
            *)
                # Use dig to dynamically obtain the IP address for other subdomains
                record_type=$(dig +short -t A "$sub.$domain" | awk '{if (NF > 0) print "A"; else print "CNAME"}')
                destination=$(dig +short "$sub.$domain")
                ;;
        esac

        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

audit_subdomain "$1" "$2"
