#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

# Update package index
sudo apt update

# Install nginx
sudo apt install nginx -y

# Configure nginx for redirection
sudo sed -i '/server_name _;/a \\nlocation /redirect_me {\n    return 301 http://example.com/destination_page;\n}' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

echo "Nginx configured for redirection successfully."

