#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# always try to automate your work!

var=$(hostname)
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

apt-get update
apt-get install nginx
vi /etc/nginx/sites-available/default
add_header server "X-Served-By";

hexToAscii(){
  #shellcheck disable=SC2154
  printf"\x$1"
}
