#!/usr/bin/env bash
# What is keeping my Ubuntu container’s Nginx installation from listening on port 80
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# Write a Bash script that configures a server to the above requirements



