#!usr/bin/env bash
# make your fix short and sweet
# Your Bash script must be 5 lines long or less
# There must be a new line at the end of the file
# You must respect usual Bash script requirements
# You cannot use ;
# You cannot use &&
# You cannot use wget
# You cannot execute your previous answer file 
# (Do not include the name of the previous script in this one)
# service (init) must say that nginx is not running ← for real
sudo apt update
sudo apt -y install net-tools (sudo netstat -tulpn | grep :80) || (sudo fuser -k 80/tcp ;
echo "server {listen 80; server_name 54.144.140.244; }" | sudo tee /etc/nginx/sites-available/default > /dev/null ; sudo systemctl restart nginx)
service nginx status | grep "not running" || echo "nginx is not running"

