#!/usr/bin/env bash
# Stop nginx if it's already running
service nginx stop
#pdate nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
# Update nginx configuration to listen on port 8080 for all IPs
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx start
# Verify nginx is running as nginx user and listening on port 8080
ps -aux | grep nginx
netstat -tuln | grep 8080
# Verify nginx is running as nginx user
# ps auxff | grep ngin[x]
# Ensure nginx is listening on all active IPs on port 8080
# nc -z 0 8080 ; echo $?
