#!/usr/bin/env bash
# creates an RSA key pair ssh-keygen -t rsa -b 4096 -C "Generated key for school" -f "$key_name" -N "betty"
echo "RSA key pair created successfully. Private key: $46265-web-01, Passphrase: betty"
